version: '3'
services:
  db:
    image: postgres
    container_name: tttn_db
    ports:
      - "5432:5432"
  web:
    build: .
    container_name: tttn_app
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/tttn
    links:
      - db
    ports:
      - "3000:3000"
    depends_on:
      - db
